version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./urls.db:/usr/src/app/urls.db
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    restart: unless-stopped
